project:
  type: website
  output-dir: docs

website:
  favicon: "img/pf.png"
  title: "C7021HF Precision farming"
  sidebar:
    logo: "img/pf.png"
    style: "docked"
    search: true
    contents: 
      - section: "Content"
        contents:
          - irrigslides.qmd
          - game.qmd
format:
  html:
    highlight-style: a11y
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual

